[DEFAULT]

[NETWORK]
default_gateway = "0.0.0.0"
subnet_mask = "255.255.255.0"
ipv4_address = "192.168.1.37"
adapter_name = "Ethernet"
adapter_prefix = "ethernet"

[DIRECTORY_CLEANERS]
dir0 = "C:/Viper"
dir1 = "C:/ViperConfigData"

[TEMPFILE_GEN]
extensions = [ ".py", ".cs", ".md", ".txt",]

[HTTP_FILE_SERVER]
user_server_name = ""
default_server_names = [ "filebeam.local", "syncbox.local", "filestop.local", "pixelstash.local", "memestream.local", "transfer.local", "quickshare.local", "sendbox.local", "echoquiet.local", "glowbytes.local", "dreamstream.local", "bitbeacon.local", "nodeload.local", "folderholder.local", "sharebear.local", "dirstop.local", "datadam.local", "billsgate.local", "datadock.local", "clipcloud.local",]
